
const SET_GENRES = 'SET_GENRES';
const TOGGLE_SEARCH_MOVIE_GENRE = 'TOGGLE_SEARCH_MOVIE_GENRE';
const CLEAR_SEARCH_MOVIE_GENRES = 'CLEAR_SEARCH_MOVIE_GENRES';
const SET_LOADING_GENRES = 'SET_LOADING_GENRES';

export {SET_GENRES, SET_LOADING_GENRES, CLEAR_SEARCH_MOVIE_GENRES, TOGGLE_SEARCH_MOVIE_GENRE};