
const SET_MOVIES = 'SET_MOVIES';
const SET_PAGINATION = 'SET_PAGINATION';
const SET_LOADING_MOVIES = 'SET_LOADING_MOVIES';
const SET_MOVIES_SEARCH = 'SET_MOVIES_SEARCH';

export {SET_MOVIES, SET_PAGINATION, SET_LOADING_MOVIES, SET_MOVIES_SEARCH};